# Generated by Django 4.2.2 on 2023-06-30 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='trabajosproducto',
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='tra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.trabajos'),
        ),
        migrations.AddField(
            model_name='trabajos',
            name='tiempo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='precio',
            field=models.CharField(max_length=50),
        ),
    ]
